name: GITHUB_OUTPUT
on: push
jobs:
  before:
    runs-on: ubuntu-latest
    steps:
      - id: create_var
        run: echo "name=ishikawa_ryo" >> "${GITHUB_OUTPUT}"
    outputs:
      name: ${{ steps.create_var.outputs.name}}
  after:
    runs-on: ubuntu-latest
    needs: before
    steps:
      - run: echo "${NAME}"
        env:
          NAME: ${{ needs.before.outputs.name}}
