name: GITHUB_OUTPUT
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - id: test
        run: |
          echo "hoge=hugahuga" >> $GITHUB_OUTPUT
      - name: print
        env:
          HOGE: ${{ steps.test.outputs.hoge }}
        run: echo "${HOGE}"
