name: GITHUB_OUTPUT
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: output
        run: |
          echo "hoge=hogehoge" >> $GITHUB_OUTPUT
      - name: print
        env:
          HOGE: ${{ steps.output.outputs.hoge }}
        run: echo "${HOGE}"
